### ISSUE TITLE
Feature request: deep state sync option

### ISSUE THREAD

**Issue by rmNyro** [vuejs/vuex-router-sync#73] opened 2017-09-27 12:41 UTC
Hi,

I'm having a hard time to solve this very simple problem: "If the user is navigation back and/or forth using builtin history action (aka history button) I want to give him back the exact same state he was at the time".

I've noticed this plugin is not for synchronizing the store state with the router state but rather gives from the store access to the router current info (state?). Btw the name is confusing to me since it doesn't sync.

Thank you in advance!

**Comment by posva** [comment] 2018-01-14 11:45
Duplicate of #56

**Closed as completed by posva** 2018-01-14 11:45 UTC
